
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - installer.h3poteto.dev
  resources:
  - ekspodidentitywebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - installer.h3poteto.dev
  resources:
  - ekspodidentitywebhooks/finalizers
  verbs:
  - update
- apiGroups:
  - installer.h3poteto.dev
  resources:
  - ekspodidentitywebhooks/status
  verbs:
  - get
  - patch
  - update
