// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonsetRef) DeepCopyInto(out *DaemonsetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonsetRef.
func (in *DaemonsetRef) DeepCopy() *DaemonsetRef {
	if in == nil {
		return nil
	}
	out := new(DaemonsetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSPodIdentityWebhook) DeepCopyInto(out *EKSPodIdentityWebhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSPodIdentityWebhook.
func (in *EKSPodIdentityWebhook) DeepCopy() *EKSPodIdentityWebhook {
	if in == nil {
		return nil
	}
	out := new(EKSPodIdentityWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EKSPodIdentityWebhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSPodIdentityWebhookList) DeepCopyInto(out *EKSPodIdentityWebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EKSPodIdentityWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSPodIdentityWebhookList.
func (in *EKSPodIdentityWebhookList) DeepCopy() *EKSPodIdentityWebhookList {
	if in == nil {
		return nil
	}
	out := new(EKSPodIdentityWebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EKSPodIdentityWebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSPodIdentityWebhookSpec) DeepCopyInto(out *EKSPodIdentityWebhookSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSPodIdentityWebhookSpec.
func (in *EKSPodIdentityWebhookSpec) DeepCopy() *EKSPodIdentityWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(EKSPodIdentityWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EKSPodIdentityWebhookStatus) DeepCopyInto(out *EKSPodIdentityWebhookStatus) {
	*out = *in
	if in.PodIdentityWebhookSecret != nil {
		in, out := &in.PodIdentityWebhookSecret, &out.PodIdentityWebhookSecret
		*out = new(SecretRef)
		**out = **in
	}
	if in.PodIdentityWebhookService != nil {
		in, out := &in.PodIdentityWebhookService, &out.PodIdentityWebhookService
		*out = new(ServiceRef)
		**out = **in
	}
	if in.PodIdentityWebhookDaemonset != nil {
		in, out := &in.PodIdentityWebhookDaemonset, &out.PodIdentityWebhookDaemonset
		*out = new(DaemonsetRef)
		**out = **in
	}
	if in.PodIdentityWebhookConfiguration != nil {
		in, out := &in.PodIdentityWebhookConfiguration, &out.PodIdentityWebhookConfiguration
		*out = new(MutatingWebhookConfigurationRef)
		**out = **in
	}
	if in.PodIdentityWebhookServiceAccount != nil {
		in, out := &in.PodIdentityWebhookServiceAccount, &out.PodIdentityWebhookServiceAccount
		*out = new(ServiceAccountRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EKSPodIdentityWebhookStatus.
func (in *EKSPodIdentityWebhookStatus) DeepCopy() *EKSPodIdentityWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(EKSPodIdentityWebhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatingWebhookConfigurationRef) DeepCopyInto(out *MutatingWebhookConfigurationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatingWebhookConfigurationRef.
func (in *MutatingWebhookConfigurationRef) DeepCopy() *MutatingWebhookConfigurationRef {
	if in == nil {
		return nil
	}
	out := new(MutatingWebhookConfigurationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ref) DeepCopyInto(out *Ref) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ref.
func (in *Ref) DeepCopy() *Ref {
	if in == nil {
		return nil
	}
	out := new(Ref)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRef) DeepCopyInto(out *ServiceAccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRef.
func (in *ServiceAccountRef) DeepCopy() *ServiceAccountRef {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRef) DeepCopyInto(out *ServiceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRef.
func (in *ServiceRef) DeepCopy() *ServiceRef {
	if in == nil {
		return nil
	}
	out := new(ServiceRef)
	in.DeepCopyInto(out)
	return out
}
